apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: jakartaee-firstcup-examples-7orm
  namespace: rhn-engineering-sstark-tenant
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload@sha256:fdd5c35a9779ecbd441833f64a88d6cdea1f2f73e0999bac6214cce83753a655
        name: container-image
        resources: {}
status: {}
