apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: jakartaee-firstcup-examples-7orm
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: jakartaee-firstcup-examples-7orm
    app.kubernetes.io/part-of: jakartaee-firstcup-examples
  name: jakartaee-firstcup-examples-7orm
  namespace: rhn-engineering-sstark-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: jakartaee-firstcup-examples-7orm
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: jakartaee-firstcup-examples-7orm
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload:11Lgl-jakartaee-firstcup-examples-7orm
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
        name: container-image
        ports:
        - containerPort: 8080
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 10
          tcpSocket:
            port: 8080
        resources:
          limits:
            cpu: "1"
            memory: 512Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
