apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: jakartaee-firstcup-examples-7orm
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: jakartaee-firstcup-examples-7orm
    app.kubernetes.io/part-of: jakartaee-firstcup-examples
  name: jakartaee-firstcup-exampl8vo6
  namespace: rhn-engineering-sstark-tenant
spec:
  port:
    targetPort: 8080
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: jakartaee-firstcup-examples-7orm
    weight: 100
status: {}
