apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: jakartaee-firstcup-examples-7orm
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: jakartaee-firstcup-examples-7orm
    app.kubernetes.io/part-of: jakartaee-firstcup-examples
  name: jakartaee-firstcup-examples-7orm
  namespace: rhn-engineering-sstark-tenant
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: jakartaee-firstcup-examples-7orm
status:
  loadBalancer: {}
